# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=25, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='LABEL', max_length=45, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=100, null=True)),
                ('picture', models.CharField(blank=True, db_column='PICTURE', max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
                ('details', models.CharField(blank=True, db_column='DETAILS', max_length=300, null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='CREATE_TIME', null=True)),
                ('discount_value', models.IntegerField(blank=True, db_column='DISCOUNT_VALUE', null=True)),
                ('discount_unit', models.CharField(blank=True, db_column='DISCOUNT_UNIT', max_length=45, null=True)),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='DiscountUser',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=25, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='CODE', max_length=45, null=True)),
                ('discount', models.ForeignKey(db_column='DISCOUNT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.Discount')),
            ],
            options={
                'db_table': 'discount_user',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=25, primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, db_column='SCORE', null=True)),
                ('content', models.TextField(db_column='CONTENT')),
                ('post_time', models.DateTimeField(db_column='POST_TIME')),
                ('pic', models.CharField(blank=True, db_column='PIC', max_length=300, null=True)),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=25, primary_key=True, serialize=False)),
                ('cell_phone', models.CharField(db_column='CELL_PHONE', max_length=15)),
                ('nick_name', models.CharField(blank=True, db_column='NICK_NAME', max_length=45, null=True)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=45, null=True)),
                ('session_id', models.CharField(blank=True, db_column='SESSION_ID', max_length=120, null=True)),
                ('latest_login', models.DateTimeField(blank=True, db_column='LATEST_LOGIN', null=True)),
                ('fetch_back_pwd', models.CharField(blank=True, db_column='FETCH_BACK_PWD', max_length=120, null=True)),
                ('account_number', models.CharField(db_column='ACCOUNT_NUMBER', max_length=45)),
                ('grade', models.CharField(blank=True, db_column='GRADE', max_length=255, null=True)),
                ('is_online', models.BooleanField(db_column='IS_ONLINE')),
                ('gender', models.CharField(blank=True, db_column='GENDER', max_length=48, null=True)),
                ('pic', models.CharField(blank=True, db_column='PIC', max_length=300, null=True)),
                ('email_addr', models.CharField(blank=True, db_column='EMAIL_ADDR', max_length=48, null=True)),
                ('type', models.CharField(blank=True, db_column='TYPE', max_length=48, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=25, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='PRODUCT_NAME', max_length=80)),
                ('picture', models.CharField(blank=True, db_column='PICTURE', max_length=300, null=True)),
                ('unit_price', models.DecimalField(blank=True, db_column='UNIT_PRICE', decimal_places=0, max_digits=10, null=True)),
                ('top_carriage_time', models.DateTimeField(blank=True, db_column='TOP_CARRIAGE_TIME', null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=25, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(db_column='SHOP_NAME', max_length=255)),
                ('floor', models.IntegerField(db_column='FLOOR')),
                ('location', models.CharField(db_column='LOCATION', max_length=255)),
                ('logo', models.CharField(db_column='LOGO', max_length=1000)),
                ('true_scene', models.CharField(blank=True, db_column='TRUE_SCENE', max_length=300, null=True)),
                ('telephone', models.CharField(db_column='TELEPHONE', max_length=20)),
                ('contact', models.CharField(db_column='CONTACT', max_length=32)),
                ('contact_tel', models.CharField(blank=True, db_column='CONTACT_TEL', max_length=20, null=True)),
                ('introduction', models.TextField(db_column='INTRODUCTION')),
                ('create_time', models.DateTimeField(db_column='CREATE_TIME')),
                ('opening_time', models.DateTimeField(blank=True, db_column='OPENING_TIME', null=True)),
                ('category', models.ForeignKey(db_column='CATEGORY_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.Category')),
                ('member', models.ForeignKey(db_column='MEMBER_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.Member')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='TypeStatus',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=25, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='LABEL', max_length=20, null=True)),
                ('short_label', models.CharField(blank=True, db_column='SHORT_LABEL', max_length=10, null=True)),
            ],
            options={
                'db_table': 'type_status',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(db_column='SHOP_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.Shop'),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.ForeignKey(db_column='STATUS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.TypeStatus'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='member',
            field=models.ForeignKey(db_column='MEMBER_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.Member'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='shop',
            field=models.ForeignKey(db_column='SHOP_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.Shop'),
        ),
        migrations.AddField(
            model_name='discountuser',
            name='member',
            field=models.ForeignKey(db_column='MEMBER_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.Member'),
        ),
        migrations.AddField(
            model_name='discountuser',
            name='status',
            field=models.ForeignKey(db_column='STATUS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.TypeStatus'),
        ),
        migrations.AddField(
            model_name='discount',
            name='shop',
            field=models.ForeignKey(db_column='SHOP_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall_admin.Shop'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('id', 'product_name')]),
        ),
    ]
